Update DallasTemperature.cpp
Due to compiler error
lib\MAX31850 DallasTemp\DallasTemperature.cpp:495:1: error: control reaches end of non-void function [-Werror=return-type]